# Build stage
FROM node:18-slim as build

# Set the working directory
WORKDIR /app

COPY Frontend/.env /app/.env

# Copy package.json and package-lock.json to install dependencies
COPY Frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Set the working directory to /app
WORKDIR /app

COPY Frontend/src /app/src

# Copy the public folder to /app
COPY Frontend/public /app/public

# Print contents of the /app/public directory
RUN ls -al /app/public

EXPOSE 3000

# Build the application
# RUN npm run build
CMD ["npm", "start"]

# Production stage
# FROM nginx:latest

# Set the working directory in the container
# WORKDIR /usr/share/nginx/html

# Copy built files from the build stage to Nginx's root directory
# COPY --from=build /app/build .

# Copy custom Nginx configuration
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port for the Web UI
# EXPOSE 80


# By default, Nginx is started automatically in the official image
