version: '3'

x-common-settings: &common-settings
  project_name: tourifyapp

services:
  frontend:
    build:
      dockerfile: Dockerfile_Frontend.txt
    ports:
      - "3000:3000"
      
    networks:
      - tourify_network
    hostname: tourify-frontend

  backend:
    build:
      dockerfile: Dockerfile_Backend.txt
    ports:
      - "8001:8001"
    networks:
      - tourify_network

  ml_model:
    build:
      dockerfile: Dockerfile_Model.txt
    ports:
      - "5000:5000"
    networks:
      - tourify_network

networks:
  tourify_network:
    driver: bridge
